### ISSUE TITLE
zip_longest not supported anymore, change to izip_longest

### ISSUE THREAD

**Issue by armaseg** [glimmerphoenix/WikiDAT#16]
Trying to execute wkidat I get the following error:

```
$ python main.py 
()
*** WIKIPEDIA DATA ANALYSIS TOOLKIT ***
()
----------------------------------------------------------
Executing ETL:RevHistory on lang: scowiki date: 20151102
ETL lines = 1 page_fan = 1 rev_fan = 1
('Download files =', True)
Start time is 2015-12-07 00:11:03 CET
----------------------------------------------------------
()
Downloading new dump files from http://dumps.wikimedia.your.org/, for language scowiki
Target URL is: http://dumps.wikimedia.your.org/scowiki/20151102
Traceback (most recent call last):
  File "main.py", line 322, in <module>
    debug=args.debug)
  File "/home/moroco/Tools/Apps/WikiDAT/WikiDAT/wikidat/tasks/tasks.py", line 129, in execute
    self.paths, self.date = self.down.download(self.date)
  File "/home/moroco/Tools/Apps/WikiDAT/WikiDAT/wikidat/tasks/download.py", line 108, in download
    for url1, url2 in itertools.zip_longest(self.dump_urls[::2],
AttributeError: 'module' object has no attribute 'zip_longest'
```

**Comment by glimmerphoenix** [comment]
Same problem here: note the `()` lines in your output. You are trying to execute the tool using Python 2 instead of Python 3. [zip_longest](https://docs.python.org/3.5/library/itertools.html#itertools.zip_longest) is the correct version of the function in Python 3.

Please, confirm to close this bug.

**Comment by armaseg** [comment]
That's right. We were using Python 2. We are switching to Python 3. You can close this bug.
