### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'span'

### ISSUE THREAD

**Issue by loretoparisi** [glimmerphoenix/WikiDAT#20]
I get this error

```
$ python main.py
()
*** WIKIPEDIA DATA ANALYSIS TOOLKIT ***
()
----------------------------------------------------------
Executing ETL:RevHistory on lang: scowiki date: 20151201
ETL lines = 1 page_fan = 1 rev_fan = 1
('Download files =', True)
Start time is 2016-10-21 10:52:32 CEST
----------------------------------------------------------
()
Downloading new dump files from http://dumps.wikimedia.your.org/, for language scowiki
Target URL is: http://dumps.wikimedia.your.org/scowiki/20151201
Traceback (most recent call last):
  File "main.py", line 322, in <module>
    debug=args.debug)
  File "/usr/local/lib/python2.7/dist-packages/WikiDAT-0.1-py2.7.egg/wikidat/tasks/tasks.py", line 129, in execute
    self.paths, self.date = self.down.download(self.date)
  File "/usr/local/lib/python2.7/dist-packages/WikiDAT-0.1-py2.7.egg/wikidat/tasks/download.py", line 88, in download
    status_dumps = soup_dumps.find('p', class_='status').spa
```

on

```
$ python --version
Python 2.7.12
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:    16.04
Codename:   xenial
```

**Comment by loretoparisi** [comment]
**[UPDATE]**
Ok it seems it was due to `Python2.7.12` so I did

```
$ virtualenv -p python3 env
$ python --version
$ python setup.py build
$ python setup.py install
```

Now I get

```
/WikiDAT/wikidat$ python main.py 
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    from wikidat.tasks import tasks
ImportError: No module named 'wikidat
```

**Comment by glimmerphoenix** [comment]
Hi Loreto,

Please, make sure that the `wikidat` module is installed correctly inside your virtual environment:
http://stackoverflow.com/questions/19048732/python-setup-py-develop-vs-install/19048754#19048754

From the error message above, it seems that python cannot find the path to load the module.

**Comment by shubham-krishna** [comment]
I am getting the same error on running with Python 3.5.2
*** WIKIPEDIA DATA ANALYSIS TOOLKIT ***

----------------------------------------------------------
Executing ETL:RevHistory on lang: scowiki date: 20151201
ETL lines = 1 page_fan = 1 rev_fan = 1
Download files = True
Start time is 2018-01-15 15:54:14 STD
----------------------------------------------------------

Downloading new dump files from http://dumps.wikimedia.your.org/, for language scowiki
Target URL is: http://dumps.wikimedia.your.org/scowiki/20151201
Traceback (most recent call last):
  File "main.py", line 322, in <module>
    debug=args.debug)
  File "/usr/local/lib/python3.5/dist-packages/WikiDAT-0.1-py3.5.egg/wikidat/tasks/tasks.py", line 129, in execute
    self.paths, self.date = self.down.download(self.date)
  File "/usr/local/lib/python3.5/dist-packages/WikiDAT-0.1-py3.5.egg/wikidat/tasks/download.py", line 88, in download
    status_dumps = soup_dumps.find('p', class_='status').span.text
AttributeError: 'NoneType' object has no attribute 'span'
